//! Hand-formatted TOML emitter for `FormState`. Hand-formatted (not
//! via serde) so we can include comments above each section pointing
//! at the fields the wizard didn't surface — Phase 1 hides eight
//! defaults (subnet, clients, dns, listen_port, namespaces, relay/
//! client targets) and the comments tell power users where to add
//! them by hand.

use std::fmt::Write;

use super::state::FormState;

/// Render `FormState` as the body of a `spec.toml` file. Always
/// well-formed TOML; `Spec::parse_str` should accept it without
/// further validation (modulo the per-field user inputs).
pub fn format_spec(state: &FormState) -> String {
    let mut out = String::new();

    let _ = writeln!(
        out,
        "# Generated by `burrowctl init`. Edit freely.\n\
         # `burrowctl validate <name>` re-checks the file end-to-end.\n"
    );

    // [wg]
    let _ = writeln!(out, "[wg]");
    let _ = writeln!(out, "endpoint = {}", quote(&state.endpoint));
    let routes = state.routes_vec();
    if routes.is_empty() {
        let _ = writeln!(out, "routes   = []");
    } else {
        let formatted: Vec<String> = routes.iter().map(|r| quote(r)).collect();
        let _ = writeln!(out, "routes   = [{}]", formatted.join(", "));
    }
    if let Some(s) = &state.subnet {
        let _ = writeln!(out, "subnet   = {}", quote(s));
    }
    if let Some(n) = &state.clients {
        let _ = writeln!(out, "clients  = {n}");
    }
    if let Some(d) = &state.dns {
        let dns_list: Vec<String> = d
            .split(',')
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
            .map(quote)
            .collect();
        let _ = writeln!(out, "dns      = [{}]", dns_list.join(", "));
    }
    if let Some(p) = &state.listen_port {
        let _ = writeln!(out, "listen_port = {p}");
    }
    // Show the hidden-defaults hint only for the fields we didn't
    // already emit above.
    let mut hidden = Vec::new();
    if state.subnet.is_none() { hidden.push("# subnet      = \"10.0.0.0/24\""); }
    if state.clients.is_none() { hidden.push("# clients     = 1"); }
    if state.dns.is_none() { hidden.push("# dns         = []"); }
    if state.listen_port.is_none() { hidden.push("# listen_port = 51820"); }
    if !hidden.is_empty() {
        let _ = writeln!(out, "# Hidden defaults — uncomment + set to override:");
        for line in hidden {
            let _ = writeln!(out, "{line}");
        }
    }

    // [transport]
    let _ = writeln!(out);
    let _ = writeln!(out, "[transport]");
    if state.wss_enabled {
        let _ = writeln!(out, "mode       = \"wss\"");
        let _ = writeln!(out, "relay_host = {}", quote(&state.relay_host));
    } else {
        let _ = writeln!(out, "mode = \"udp\"");
    }

    // [build.gateway]
    let _ = writeln!(out);
    let _ = writeln!(out, "[build.gateway]");
    let _ = writeln!(out, "target = {}", quote(&state.gateway_target));
    if let Some(t) = &state.relay_target {
        let _ = writeln!(out);
        let _ = writeln!(out, "[build.relay]");
        let _ = writeln!(out, "target = {}", quote(t));
    }
    if let Some(t) = &state.client_target {
        let _ = writeln!(out);
        let _ = writeln!(out, "[build.client]");
        let _ = writeln!(out, "target = {}", quote(t));
    }
    if state.relay_target.is_none() && state.client_target.is_none() {
        let _ = writeln!(
            out,
            "# Hidden defaults: [build.relay].target and [build.client].target\n\
             # both default to \"x86_64-unknown-linux-gnu\". Override per-binary."
        );
    }

    // [deploy]
    if state.deploy_enabled {
        let _ = writeln!(out);
        let _ = writeln!(out, "[deploy.server]");
        let _ = writeln!(out, "host = {}", quote(&state.deploy_host));
        if let Some(ns) = &state.server_namespace {
            let _ = writeln!(out, "namespace = {}", quote(ns));
        } else {
            let _ = writeln!(out, "# Hidden default: namespace = \"burrow\"");
        }
        let _ = writeln!(out);
        let _ = writeln!(out, "[deploy.client]");
        if let Some(ns) = &state.client_namespace {
            let _ = writeln!(out, "namespace = {}", quote(ns));
        } else {
            let _ = writeln!(out, "# Hidden default: namespace = \"burrow\"");
        }
    } else {
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "# Uncomment to enable `burrowctl ship-server` / `up` / `down`:\n\
             # [deploy.server]\n\
             # host = \"vpn.example.com\""
        );
    }

    out
}

/// TOML string-quoting that doesn't bother handling backslashes,
/// newlines, etc. — the wizard fields are all short host:port,
/// hostnames, CIDRs, or target triples; none of them legitimately
/// contain a `"` or `\`. If a user finds a way to inject one we'd
/// catch it on the post-emit `Spec::parse_str` gate.
fn quote(s: &str) -> String {
    format!("\"{s}\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::Spec;

    fn base() -> FormState {
        FormState {
            endpoint: "vpn.example.com:51820".into(),
            gateway_target: "x86_64-unknown-linux-gnu".into(),
            deploy_enabled: false,
            deploy_host: String::new(),
            wss_enabled: false,
            relay_host: String::new(),
            routes: String::new(),
            subnet: None,
            clients: None,
            listen_port: None,
            dns: None,
            server_namespace: None,
            client_namespace: None,
            relay_target: None,
            client_target: None,
        }
    }

    #[test]
    fn udp_no_deploy_round_trips() {
        let s = base();
        let body = format_spec(&s);
        let parsed = Spec::parse_str(&body).unwrap();
        assert_eq!(parsed.wg.endpoint, "vpn.example.com:51820");
        assert!(parsed.deploy.is_none());
    }

    #[test]
    fn udp_with_deploy_round_trips() {
        let mut s = base();
        s.deploy_enabled = true;
        s.deploy_host = "vpn.example.com".into();
        let body = format_spec(&s);
        let parsed = Spec::parse_str(&body).unwrap();
        let d = parsed.deploy.unwrap();
        assert_eq!(d.server.host, "vpn.example.com");
        assert_eq!(d.server.namespace, "burrow"); // default kicks in
    }

    #[test]
    fn wss_no_deploy_round_trips() {
        let mut s = base();
        s.wss_enabled = true;
        s.relay_host = "vpn.example.com:443".into();
        let body = format_spec(&s);
        let parsed = Spec::parse_str(&body).unwrap();
        assert_eq!(
            parsed.transport.relay_host.as_deref(),
            Some("vpn.example.com:443")
        );
    }

    #[test]
    fn wss_with_deploy_round_trips() {
        let mut s = base();
        s.deploy_enabled = true;
        s.deploy_host = "vpn.example.com".into();
        s.wss_enabled = true;
        s.relay_host = "vpn.example.com:443".into();
        s.routes = "192.168.1.0/24, 10.50.0.0/24".into();
        let body = format_spec(&s);
        let parsed = Spec::parse_str(&body).unwrap();
        assert!(parsed.deploy.is_some());
        assert_eq!(parsed.wg.routes, vec!["192.168.1.0/24", "10.50.0.0/24"]);
    }

    #[test]
    fn empty_routes_emit_empty_list() {
        let s = base();
        let body = format_spec(&s);
        assert!(body.contains("routes   = []"));
    }

    #[test]
    fn advanced_overrides_emit_explicitly_and_round_trip() {
        let mut s = base();
        s.subnet = Some("10.50.0.0/24".into());
        s.clients = Some("3".into());
        s.listen_port = Some("51900".into());
        s.dns = Some("1.1.1.1, 9.9.9.9".into());
        s.relay_target = Some("x86_64-unknown-linux-musl".into());
        s.client_target = Some("aarch64-unknown-linux-gnu".into());
        s.deploy_enabled = true;
        s.deploy_host = "vpn.example.com".into();
        s.server_namespace = Some("burrow-prod".into());
        s.client_namespace = Some("burrow-test".into());
        let body = format_spec(&s);
        let parsed = Spec::parse_str(&body).unwrap();
        assert_eq!(parsed.wg.subnet, "10.50.0.0/24");
        assert_eq!(parsed.wg.clients, 3);
        assert_eq!(parsed.wg.listen_port, 51900);
        assert_eq!(parsed.wg.dns, vec!["1.1.1.1", "9.9.9.9"]);
        assert_eq!(parsed.build.relay.target, "x86_64-unknown-linux-musl");
        assert_eq!(parsed.build.client.target, "aarch64-unknown-linux-gnu");
        let d = parsed.deploy.unwrap();
        assert_eq!(d.server.namespace, "burrow-prod");
        assert_eq!(d.client.namespace, "burrow-test");
    }

    #[test]
    fn output_is_human_readable() {
        // Spot-check: the Hidden defaults comments land somewhere
        // reasonable so power users find them.
        let s = base();
        let body = format_spec(&s);
        assert!(body.contains("# Hidden defaults"), "{body}");
        assert!(body.contains("# Generated by `burrowctl init`"), "{body}");
    }
}
